In [2]:
import pandas as pd
from datetime import datetime as dt

In [3]:
original_tweets = pd.read_csv("D:/Practicum1/tweets.csv")

In [4]:
original_tweets.head()

,Unnamed: 0,0,1,2,3
0,0,1079527504325406720,sherianbird,"Yeah right, #DumbassGovBrown Men fought in WWI...",2018-12-30 23:59:48+00:00
1,1,1079527402727006208,Grumpy_Paddy,One bee doesn't make climate change. Bees have...,2018-12-30 23:59:24+00:00
2,2,1079527384397856769,MalphasEternal,Ken also conveniently forgets that there are i...,2018-12-30 23:59:19+00:00
3,3,1079527360012189696,teambernie27001,Climate Change is a crisis requiring immediate...,2018-12-30 23:59:13+00:00
4,4,1079527333357330432,ArchitectsDCA,You know that #capandtrade is the best model f...,2018-12-30 23:59:07+00:00

In [5]:
for col in original_tweets.columns: 
    print(col)

Unnamed: 0
0
1
2
3

In [6]:
tweets=original_tweets.rename(columns={"Unnamed: 0": "row_id", "0": "tweet_id","1":"username", "2":"text","3":"date_time"})
tweets.head()

,row_id,tweet_id,username,text,date_time
0,0,1079527504325406720,sherianbird,"Yeah right, #DumbassGovBrown Men fought in WWI...",2018-12-30 23:59:48+00:00
1,1,1079527402727006208,Grumpy_Paddy,One bee doesn't make climate change. Bees have...,2018-12-30 23:59:24+00:00
2,2,1079527384397856769,MalphasEternal,Ken also conveniently forgets that there are i...,2018-12-30 23:59:19+00:00
3,3,1079527360012189696,teambernie27001,Climate Change is a crisis requiring immediate...,2018-12-30 23:59:13+00:00
4,4,1079527333357330432,ArchitectsDCA,You know that #capandtrade is the best model f...,2018-12-30 23:59:07+00:00

In [7]:
tweets.dtypes

row_id        int64
tweet_id      int64
username     object
text         object
date_time    object
dtype: object

In [8]:
tweets['date_time']=pd.to_datetime(tweets['date_time'])
tweets.dtypes

row_id                     int64
tweet_id                   int64
username                  object
text                      object
date_time    datetime64[ns, UTC]
dtype: object

In [9]:
tweets.head()

,row_id,tweet_id,username,text,date_time
0,0,1079527504325406720,sherianbird,"Yeah right, #DumbassGovBrown Men fought in WWI...",2018-12-30 23:59:48+00:00
1,1,1079527402727006208,Grumpy_Paddy,One bee doesn't make climate change. Bees have...,2018-12-30 23:59:24+00:00
2,2,1079527384397856769,MalphasEternal,Ken also conveniently forgets that there are i...,2018-12-30 23:59:19+00:00
3,3,1079527360012189696,teambernie27001,Climate Change is a crisis requiring immediate...,2018-12-30 23:59:13+00:00
4,4,1079527333357330432,ArchitectsDCA,You know that #capandtrade is the best model f...,2018-12-30 23:59:07+00:00

In [10]:
tweets2=tweets.drop(columns=['row_id'])
tweets2.head()

,tweet_id,username,text,date_time
0,1079527504325406720,sherianbird,"Yeah right, #DumbassGovBrown Men fought in WWI...",2018-12-30 23:59:48+00:00
1,1079527402727006208,Grumpy_Paddy,One bee doesn't make climate change. Bees have...,2018-12-30 23:59:24+00:00
2,1079527384397856769,MalphasEternal,Ken also conveniently forgets that there are i...,2018-12-30 23:59:19+00:00
3,1079527360012189696,teambernie27001,Climate Change is a crisis requiring immediate...,2018-12-30 23:59:13+00:00
4,1079527333357330432,ArchitectsDCA,You know that #capandtrade is the best model f...,2018-12-30 23:59:07+00:00

In [11]:
tweets2['tweet_id'].count()

10899

In [12]:
tweets2['tweet_id'].nunique()

10873

In [13]:
tweets2.drop_duplicates(subset='tweet_id',keep='first',inplace=True)

In [14]:
tweets2['tweet_id'].count()

10873

In [15]:
tweets2['tweet_id'].nunique()

10873

In [16]:
tweets2['username'].nunique()

9533

In [17]:
tweets2['month']=tweets2['date_time'].dt.month

In [18]:
tweets2.groupby('month')['tweet_id'].count()

month
1     1034
2      818
3      913
4      886
5      910
6      875
7      896
8      898
9      880
10     902
11     887
12     974
Name: tweet_id, dtype: int64

In [19]:
tweets2['day']=tweets2['date_time'].dt.day

In [20]:
tweets2[tweets2['month']==1].groupby('day')['tweet_id'].count()
#data[data['item'] == 'call'].groupby('network')['duration'].sum()

day
1     60
2     58
3     58
4     59
5     30
6     30
7     30
8     29
9     29
10    30
11    30
12    30
13    29
14    29
15    30
16    30
17    29
18    30
19    29
20    30
21    29
22    30
23    30
24    30
25    30
26    29
27    29
28    28
29    30
30    30
31    30
Name: tweet_id, dtype: int64

In [21]:
tweets2[(tweets2['day']==1) & (tweets2['month']==1)]

,tweet_id,username,text,date_time,month,day
20,1080252273236664320,LaurenBolton3,That human beings make a significant impact on...,2019-01-01 23:59:46+00:00,1,1
21,1080252264915316743,jeffwhelpley,"In the short term, no doubt that Trump and the...",2019-01-01 23:59:44+00:00,1,1
22,1080252242068951041,NathanWurtzel,"OK, well judging by your response to 9/11, we'...",2019-01-01 23:59:39+00:00,1,1
23,1080252227632021504,GovtsTheProblem,Not as generous as taxpayers. Over $13 billion...,2019-01-01 23:59:35+00:00,1,1
24,1080252208803766272,iamlordyaya,Is Dave Rubin indirectly denying man-made clim...,2019-01-01 23:59:31+00:00,1,1
25,1080252208439091201,climatedynamics,Cleaning up steel is key to tackling climate c...,2019-01-01 23:59:31+00:00,1,1
26,1080252183831080963,duckman11791,If you deny climate change exists. You essenti...,2019-01-01 23:59:25+00:00,1,1
27,1080252167334887424,ryanmrichardson,I think they're attributing more left-wing ide...,2019-01-01 23:59:21+00:00,1,1
28,1080252147516743680,ExNinja95,Climate change is a Marxist hoax.,2019-01-01 23:59:16+00:00,1,1
29,1080252130252906497,Yvonne4NE,Reports released last week indicate that the L...,2019-01-01 23:59:12+00:00,1,1
370,1080251185066430464,AMprefersPM,Not unless he adopts policies that will provid...,2019-01-01 23:55:27+00:00,1,1
371,1080250262827253760,Ryan_LR,A small thing I'm going to try more is saying ...,2019-01-01 23:51:47+00:00,1,1
372,1080248227809488897,CascadiaCAN,"“Thanks to #GreenNewDeal, Progressives Forced ...",2019-01-01 23:43:42+00:00,1,1
373,1080247600937353216,JTurner423,"Climate Crisis Is “Existential Threat,” House ...",2019-01-01 23:41:12+00:00,1,1
374,1080246860906934273,JavierV_Sanchez,Alexandria Ocasio-Cortez: Pelosi's Climate Cri...,2019-01-01 23:38:16+00:00,1,1
375,1080246153734733824,LAProgressive,#RT @theintercept: The new House committee bei...,2019-01-01 23:35:27+00:00,1,1
376,1080244894936059909,GrahamRoth,The climate crisis is radical. It requires bol...,2019-01-01 23:30:27+00:00,1,1
377,1080244746604417024,DebbieGei,Huh? You are an environMENTAL disaster. You do...,2019-01-01 23:29:52+00:00,1,1
378,1080244633706192898,JavierV_Sanchez,Alexandria Ocasio-Cortez: Pelosi's Climate Cri...,2019-01-01 23:29:25+00:00,1,1
379,1080244489191604224,buddy_dek,"Nancy Pelosi calls the climate crisis an ""exis...",2019-01-01 23:28:50+00:00,1,1
716,1080252227862749184,America01st,"""Global WARMING"" strikes again. . . .",2019-01-01 23:59:35+00:00,1,1
717,1080252085629829120,EthanFaatz,Great Grandpa’s thoughts on global warming “Th...,2019-01-01 23:59:01+00:00,1,1
718,1080252039857287170,MaxGraham,Are we still talking about a silver bullet for...,2019-01-01 23:58:51+00:00,1,1
719,1080252025684852736,PhilosopherSue,"#GlobalWarming Harms Animals In the Antarctic,...",2019-01-01 23:58:47+00:00,1,1
720,1080251941333151745,PhilosopherSue,"#GlobalWarming Harms Animals. In the Arctic, l...",2019-01-01 23:58:27+00:00,1,1
721,1080251882164183041,actual_chaos,Not the planet. The sun. The only way to stop ...,2019-01-01 23:58:13+00:00,1,1
722,1080251742363795456,DarrellArkas,Global warming...,2019-01-01 23:57:40+00:00,1,1
723,1080251237986111493,villavyx,#APES4 @LoraxPmhs v.villatoro cars emit carbon...,2019-01-01 23:55:39+00:00,1,1
724,1080251227424915459,pinangodan,Australian Senator exposes Man Made Global War...,2019-01-01 23:55:37+00:00,1,1
725,1080251159359692801,SergeantMajor05,In a special “Meet the Press” episode dedicate...,2019-01-01 23:55:21+00:00,1,1
10175,1212523897964285953,howard_gewirtz,I’m sure they’ll be delighted to see him. Will...,2020-01-01 23:59:59+00:00,1,1
10176,1212523891748327424,jono_nath,A bit of perspective. 100% of fires made worse...,2020-01-01 23:59:58+00:00,1,1
10177,1212523871028600832,IAM__Network,IAM Platform Curated Tweet: Year In Review: Fi...,2020-01-01 23:59:53+00:00,1,1
10178,1212523861247504389,wgbhnews,States are stepping up their efforts to curb c...,2020-01-01 23:59:50+00:00,1,1
10179,1212523859917717504,dontworry66,And any mention of Daniel Andrews going awol d...,2020-01-01 23:59:50+00:00,1,1
10180,1212523833015644161,manwithoutatan,"So, if you were wondering why I keep yelling t...",2020-01-01 23:59:44+00:00,1,1
10181,1212523811020713984,manwithoutatan,The Australian government refuses to discuss t...,2020-01-01 23:59:38+00:00,1,1
10182,1212523800446693378,jocksjig,"Australia, your country is burning – dangerous...",2020-01-01 23:59:36+00:00,1,1
10183,1212523796265091073,jbkenn,@Taraustralis There are 3 parts to a Fire &amp...,2020-01-01 23:59:35+00:00,1,1
10184,1212523771707289601,iamsammaher,Australia's Angry Summer: This Is What Climate...,2020-01-01 23:59:29+00:00,1,1
10519,1212523807065477125,SemiSmartHuman2,You're also a climate crisis denier so your op...,2020-01-01 23:59:37+00:00,1,1
10520,1212523758566748160,dllundy1,"So, Leah, do you know what would happen if the...",2020-01-01 23:59:26+00:00,1,1
10521,1212523426767876104,basementvegan,Did the world get better or worse in the 2010s...,2020-01-01 23:58:07+00:00,1,1
10522,1212522994628775936,Geoelte_Spinne,"Give this thread a read, and weep at what we'v...",2020-01-01 23:56:24+00:00,1,1
10523,1212522948856184832,rodwilliams8,Stop the LNP/right propaganda and admit that c...,2020-01-01 23:56:13+00:00,1,1
10524,1212522910276935681,JimBair62221006,Pacific Northwest Forests Fit Trifecta for Cur...,2020-01-01 23:56:04+00:00,1,1
10525,1212522907001380864,MichaelPlatt85,ExxonMobil Wishes Australia A 'Fun' New Year A...,2020-01-01 23:56:03+00:00,1,1
10526,1212522862306742274,DebErupts,"Australia, your country is burning – dangerous...",2020-01-01 23:55:52+00:00,1,1
10527,1212522706765275136,LaurishaCuba,RT En varios países del mundo etiquetas como #...,2020-01-01 23:55:15+00:00,1,1
10528,1212522584681500675,Jessie42292067,Distancing himself from PPC members is NOT a s...,2020-01-01 23:54:46+00:00,1,1
10861,1212523646935355392,Dfran1000David,Conservative girls and @rohll5 should not be b...,2020-01-01 23:58:59+00:00,1,1
10862,1212523633572118528,springytaee,i won’t turn 18 because global warming,2020-01-01 23:58:56+00:00,1,1
10863,1212523547106648064,M0rganp3rry,Or the world may end from global warming haha ...,2020-01-01 23:58:35+00:00,1,1
10864,1212523356047605760,HelenClarkNZ,"Tragic to see what is happening to people, the...",2020-01-01 23:57:50+00:00,1,1
10865,1212523317883748353,Imsmithy991,For 40 years the unhappy and unhinged left has...,2020-01-01 23:57:41+00:00,1,1
10866,1212523295226118144,SOPETOES,Global warming isn’t real them fairies in Neve...,2020-01-01 23:57:35+00:00,1,1
10867,1212523210371141637,warmerdaze,More global warming.,2020-01-01 23:57:15+00:00,1,1
10868,1212523072009515008,Globalisation9,"I have the technology for global warming, rene...",2020-01-01 23:56:42+00:00,1,1
10869,1212523024324251648,Foghorn23782542,Now this is how you welcome the new year in Ca...,2020-01-01 23:56:31+00:00,1,1
10870,1212522944104058880,wiseoldmrowl,Well it shows that he got at least somethings ...,2020-01-01 23:56:12+00:00,1,1

In [22]:
tweets2['year']=tweets2['date_time'].dt.year

In [23]:
tweets3=tweets2[tweets2['year']==2019]

In [24]:
tweets3.groupby('month')['tweet_id'].count()

month
1     917
2     818
3     913
4     886
5     910
6     875
7     896
8     898
9     880
10    902
11    887
12    914
Name: tweet_id, dtype: int64

In [25]:
tweets3['change']=tweets3['text'].str.contains('climate change|climatechange')

C:\Users\jelin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [26]:
tweets3['crisis']=tweets3['text'].str.contains('climate crisis|climatecrisis')

C:\Users\jelin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [27]:
tweets3['gw']=tweets3['text'].str.contains('global warming|globalwarming')

C:\Users\jelin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [28]:
tweets3.groupby('change')['tweet_id'].count()

change
False    7684
True     3007
Name: tweet_id, dtype: int64

In [29]:
tweets3.groupby('crisis')['tweet_id'].count()

crisis
False    8722
True     1969
Name: tweet_id, dtype: int64

In [30]:
tweets3.groupby('gw')['tweet_id'].count()

gw
False    8241
True     2450
Name: tweet_id, dtype: int64

In [31]:
tweets3['date']=tweets3['date_time'].dt.strftime("%x")

C:\Users\jelin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [32]:
# tweets3['date_group']=['pre_season' if x < '06/26/19' else 'other' for x in tweets3['date']]

C:\Users\jelin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [50]:
tweets3.loc[(tweets3['date'] <  '06/26/19'), 'date_group']='pre-season'  
tweets3.loc[(tweets3['date'] < '10/01/19') & (tweets3['date'] >= '06/26/19'), 'date_group'] = 'na_only' 
tweets3.loc[(tweets3['date'] < '11/11/19') & (tweets3['date'] >= '10/01/19'), 'date_group'] = 'national_season'
tweets3.loc[(tweets3['date'] < '12/18/19') & (tweets3['date'] >= '11/11/19'), 'date_group'] = 'SOE_start'
tweets3.loc[(tweets3['date'] >= '12/18/19'), 'date_group'] = 'rly_hot'

In [51]:
tweets3.groupby('date_group')['tweet_id'].count()

date_group
SOE_start          1090
na_only            2821
national_season    1198
pre-season         5172
rly_hot             415
Name: tweet_id, dtype: int64

In [52]:
tweets3.head()

,tweet_id,username,text,date_time,month,day,year,change,crisis,gw,date,date_group
20,1080252273236664320,LaurenBolton3,That human beings make a significant impact on...,2019-01-01 23:59:46+00:00,1,1,2019,True,False,False,01/01/19,pre-season
21,1080252264915316743,jeffwhelpley,"In the short term, no doubt that Trump and the...",2019-01-01 23:59:44+00:00,1,1,2019,True,False,False,01/01/19,pre-season
22,1080252242068951041,NathanWurtzel,"OK, well judging by your response to 9/11, we'...",2019-01-01 23:59:39+00:00,1,1,2019,True,False,False,01/01/19,pre-season
23,1080252227632021504,GovtsTheProblem,Not as generous as taxpayers. Over $13 billion...,2019-01-01 23:59:35+00:00,1,1,2019,True,False,False,01/01/19,pre-season
24,1080252208803766272,iamlordyaya,Is Dave Rubin indirectly denying man-made clim...,2019-01-01 23:59:31+00:00,1,1,2019,True,False,False,01/01/19,pre-season